import type { AnalyticsDefinition } from "@/lib/analytics/types";
import { ANALYTICS_MIN_SAMPLE } from "@/lib/analytics/sample";

export const ANALYTICS_REGISTRY: AnalyticsDefinition[] = [
  {
    id: "performance_scorecard",
    title: "Performance scorecard",
    category: "performance",
    tier: "essential",
    description: "Core profitability and consistency KPIs for the filtered sample.",
    primaryQuestion: "Am I making money?",
    traderValue: "Immediate clarity on profitability, win rate, and expectancy.",
    minimumSampleSize: 1,
    chartType: "metric",
    insightEnabled: true,
    drilldownEnabled: true,
    pages: ["overview", "performance"],
  },
  {
    id: "equity_curve",
    title: "Equity curve",
    category: "performance",
    tier: "essential",
    description: "Cumulative net equity over time with trade markers.",
    primaryQuestion: "Is my account growing consistently?",
    traderValue: "Visual trend of account growth and volatility.",
    minimumSampleSize: 2,
    chartType: "line",
    insightEnabled: true,
    drilldownEnabled: true,
    pages: ["overview", "performance", "risk"],
  },
  {
    id: "win_loss_breakdown",
    title: "Win / loss / breakeven",
    category: "performance",
    tier: "essential",
    description: "Outcome mix across closed trades.",
    primaryQuestion: "How often do I win vs lose?",
    traderValue: "Understand outcome frequency before diving into R distributions.",
    minimumSampleSize: 1,
    chartType: "stacked_bar",
    insightEnabled: true,
    drilldownEnabled: true,
    pages: ["overview", "performance"],
  },
  {
    id: "gross_profit_vs_loss",
    title: "Gross profit vs gross loss",
    category: "performance",
    tier: "essential",
    description: "Total winning P&L compared with total losing P&L.",
    primaryQuestion: "Are my winners bigger than my losers overall?",
    traderValue: "Shows whether profit factor strength comes from win size or frequency.",
    minimumSampleSize: 1,
    chartType: "bar",
    insightEnabled: true,
    pages: ["overview", "performance"],
  },
  {
    id: "avg_win_vs_loss",
    title: "Average win vs average loss",
    category: "performance",
    tier: "essential",
    description: "Typical winner size compared with typical loser size.",
    primaryQuestion: "How much do I typically make or lose per trade?",
    traderValue: "Payoff ratio context for expectancy interpretation.",
    minimumSampleSize: 1,
    chartType: "bar",
    insightEnabled: true,
    pages: ["overview", "performance"],
  },
  {
    id: "long_vs_short",
    title: "Long vs short",
    category: "performance",
    tier: "essential",
    description: "Directional performance comparison.",
    primaryQuestion: "Which direction works better for me?",
    traderValue: "Identify directional bias in observed results.",
    minimumSampleSize: 3,
    chartType: "bar",
    insightEnabled: true,
    drilldownEnabled: true,
    pages: ["overview", "performance"],
  },
  {
    id: "best_worst_trades",
    title: "Best & worst trades",
    category: "performance",
    tier: "essential",
    description: "Ranked largest winners and losers.",
    primaryQuestion: "What trades drove my results?",
    traderValue: "Quick review of outliers without statistical complexity.",
    minimumSampleSize: 1,
    chartType: "table",
    insightEnabled: false,
    pages: ["overview", "performance"],
  },
  {
    id: "instrument_performance",
    title: "Instrument performance",
    category: "edge",
    tier: "essential",
    description: "Ranked instrument results.",
    primaryQuestion: "Which instruments contribute most to my edge?",
    traderValue: "Focus review on symbols with the strongest observed expectancy.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "horizontal_bar",
    insightEnabled: true,
    drilldownEnabled: true,
    pages: ["overview", "edge"],
  },
  {
    id: "setup_performance",
    title: "Setup performance",
    category: "edge",
    tier: "essential",
    description: "Ranked setup results.",
    primaryQuestion: "Which setups show the strongest historical results?",
    traderValue: "Historical setup comparison — not a trade recommendation.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "horizontal_bar",
    insightEnabled: true,
    drilldownEnabled: true,
    pages: ["overview", "edge"],
  },
  {
    id: "session_performance",
    title: "Session performance",
    category: "edge",
    tier: "essential",
    description: "Ranked session results.",
    primaryQuestion: "When do I trade best?",
    traderValue: "Session-level expectancy for time-of-day review.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "horizontal_bar",
    insightEnabled: true,
    drilldownEnabled: true,
    pages: ["overview", "edge"],
  },
  {
    id: "trade_habits",
    title: "Trade habits",
    category: "execution",
    tier: "essential",
    description: "Activity frequency and common hold-time / size buckets.",
    primaryQuestion: "How active am I, and how long do I hold trades?",
    traderValue: "Observed trading patterns — association, not causation.",
    minimumSampleSize: 1,
    chartType: "metric",
    insightEnabled: true,
    pages: ["overview", "execution"],
  },
  {
    id: "cost_bridge",
    title: "Gross to net bridge",
    category: "costs",
    tier: "essential",
    description: "Commission and swap impact on gross P&L.",
    primaryQuestion: "How much did trading costs reduce my gross performance?",
    traderValue: "Cost drag awareness before optimizing entries and exits.",
    minimumSampleSize: 1,
    chartType: "bar",
    insightEnabled: true,
    pages: ["overview", "performance"],
  },
  {
    id: "r_distribution",
    title: "R-multiple distribution",
    category: "performance",
    tier: "quant",
    description: "Histogram of trade R outcomes with percentiles.",
    primaryQuestion: "How are my trade outcomes distributed?",
    traderValue: "Tail risk and consistency research.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "histogram",
    insightEnabled: true,
    drilldownEnabled: true,
    pages: ["performance", "quant_lab"],
  },
  {
    id: "rolling_expectancy",
    title: "Rolling expectancy",
    category: "research",
    tier: "quant",
    description: "Expectancy over a rolling trade window.",
    primaryQuestion: "Is my edge stable or changing over time?",
    traderValue: "Detect regime shifts in observed performance.",
    minimumSampleSize: 30,
    chartType: "line",
    insightEnabled: true,
    methodology: "Rolling window expectancy across sequential closed trades.",
    pages: ["quant_lab"],
  },
  {
    id: "monte_carlo",
    title: "Monte Carlo simulation",
    category: "research",
    tier: "quant",
    description: "Resampled equity paths from historical trade outcomes.",
    primaryQuestion: "What range of equity paths is plausible from this sample?",
    traderValue: "Stress-test sequence risk — not a forecast.",
    minimumSampleSize: 5,
    chartType: "line",
    insightEnabled: true,
    methodology: "Monte Carlo resamples historical trade outcomes to estimate possible equity paths.",
    pages: ["quant_lab"],
  },
  {
    id: "mfe_mae_scatter",
    title: "MFE vs MAE",
    category: "execution",
    tier: "deep_dive",
    description: "Maximum favorable vs adverse excursion scatter.",
    primaryQuestion: "How much favorable movement do I capture vs tolerate?",
    traderValue: "Execution quality and exit timing diagnostics.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "scatter",
    insightEnabled: true,
    drilldownEnabled: true,
    pages: ["execution"],
  },
  {
    id: "exit_efficiency",
    title: "Exit efficiency",
    category: "execution",
    tier: "deep_dive",
    description: "How much of favorable movement is captured at exit.",
    primaryQuestion: "Am I leaving too much on the table on winners?",
    traderValue: "Exit timing review alongside MFE analysis.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "histogram",
    insightEnabled: true,
    pages: ["execution"],
  },
  {
    id: "period_comparison",
    title: "Period comparison",
    category: "performance",
    tier: "deep_dive",
    description: "Current period vs prior period metric deltas.",
    primaryQuestion: "Is my performance improving or deteriorating?",
    traderValue: "Context for whether recent changes are helping.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "metric",
    insightEnabled: true,
    pages: ["performance"],
  },
  {
    id: "consistency_lab",
    title: "Consistency metrics",
    category: "performance",
    tier: "deep_dive",
    description: "Day and week consistency statistics.",
    primaryQuestion: "How consistent are my daily and weekly results?",
    traderValue: "Stability context beyond headline P&L.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "metric",
    insightEnabled: true,
    pages: ["performance"],
  },
  {
    id: "time_of_day",
    title: "Time of day performance",
    category: "edge",
    tier: "essential",
    description: "Hourly expectancy and win rate patterns.",
    primaryQuestion: "Which hours show the strongest results?",
    traderValue: "Time-of-day review without statistical complexity by default.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "bar",
    insightEnabled: true,
    drilldownEnabled: true,
    pages: ["edge"],
  },
  {
    id: "time_heatmap",
    title: "Day × hour heatmap",
    category: "edge",
    tier: "deep_dive",
    description: "Expectancy heatmap by weekday and hour.",
    primaryQuestion: "When exactly do my best and worst results cluster?",
    traderValue: "Fine-grained temporal edge discovery.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "heatmap",
    insightEnabled: true,
    pages: ["edge"],
  },
  {
    id: "position_size_buckets",
    title: "Position size buckets",
    category: "execution",
    tier: "deep_dive",
    description: "Expectancy by relative position size bucket.",
    primaryQuestion: "Do larger or smaller positions perform better?",
    traderValue: "Sizing discipline review.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "bar",
    insightEnabled: true,
    pages: ["execution"],
  },
  {
    id: "duration_buckets",
    title: "Duration buckets",
    category: "execution",
    tier: "deep_dive",
    description: "Expectancy by holding time segment.",
    primaryQuestion: "Which hold times work best for me?",
    traderValue: "Hold-time pattern review — association, not causation.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "bar",
    insightEnabled: true,
    pages: ["execution"],
  },
  {
    id: "risk_vs_result",
    title: "Risk vs result",
    category: "execution",
    tier: "deep_dive",
    description: "Risk percent plotted against realized R.",
    primaryQuestion: "Does risk size relate to outcomes in this sample?",
    traderValue: "Risk discipline scatter diagnostic.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "scatter",
    insightEnabled: true,
    pages: ["execution"],
  },
  {
    id: "calendar_heatmap",
    title: "Trading calendar",
    category: "calendar",
    tier: "essential",
    description: "Daily P&L calendar view.",
    primaryQuestion: "Which days contributed most to my results?",
    traderValue: "Temporal pattern spotting at a glance.",
    minimumSampleSize: 1,
    chartType: "heatmap",
    insightEnabled: true,
    pages: ["calendar"],
  },
  {
    id: "streak_distribution",
    title: "Streak distribution",
    category: "behaviour",
    tier: "quant",
    description: "Win and loss streak frequency from sequential closed trades.",
    primaryQuestion: "How often do loss streaks of different lengths occur historically?",
    traderValue: "Context for drawdown psychology — not a stop-trading rule.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "histogram",
    insightEnabled: false,
    methodology: "Counts loss streak lengths across the filtered trade sequence. Frequencies are descriptive.",
    pages: ["quant_lab"],
  },
  {
    id: "rolling_expectancy",
    title: "Rolling expectancy",
    category: "performance",
    tier: "quant",
    description: "Rolling-window expectancy and win rate over trade sequence.",
    primaryQuestion: "Is my edge stable or drifting over time?",
    traderValue: "Detect regime shifts and recent performance drift.",
    minimumSampleSize: 20,
    chartType: "line",
    insightEnabled: false,
    methodology: "Computes expectancy R and win rate over a fixed trade-count window, stepped trade by trade.",
    pages: ["quant_lab"],
  },
  {
    id: "bootstrap_expectancy",
    title: "Bootstrap expectancy",
    category: "performance",
    tier: "quant",
    description: "Resampled distribution of expectancy R with confidence interval.",
    primaryQuestion: "How uncertain is my observed expectancy given this sample?",
    traderValue: "Separates point estimate from sampling uncertainty.",
    minimumSampleSize: 5,
    chartType: "histogram",
    insightEnabled: false,
    methodology: "Bootstrap resampling with replacement (5,000 iterations). Reports median and percentile interval.",
    pages: ["quant_lab"],
  },
  {
    id: "win_rate_ci",
    title: "Win rate confidence interval",
    category: "performance",
    tier: "quant",
    description: "Wilson score interval for observed win rate.",
    primaryQuestion: "What win-rate range is consistent with this sample?",
    traderValue: "Avoid over-interpreting win rate from small samples.",
    minimumSampleSize: 5,
    chartType: "metric",
    insightEnabled: false,
    methodology: "Wilson score interval at 95% confidence for binomial win proportion.",
    pages: ["quant_lab"],
  },
  {
    id: "return_distribution",
    title: "Return distribution",
    category: "performance",
    tier: "quant",
    description: "R-multiple and currency return histograms with distribution statistics.",
    primaryQuestion: "What does the shape of my return distribution look like?",
    traderValue: "Tail risk, skew, and outlier context beyond averages.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "histogram",
    insightEnabled: false,
    methodology: "Descriptive histogram and moment statistics on validated per-trade returns.",
    pages: ["quant_lab"],
  },
  {
    id: "outlier_dependency",
    title: "Outlier dependency",
    category: "performance",
    tier: "quant",
    description: "Share of net profit from top trades and counterfactual removal.",
    primaryQuestion: "Does my edge depend on a few exceptional trades?",
    traderValue: "Fragility check before trusting headline expectancy.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "metric",
    insightEnabled: false,
    methodology: "Measures profit contribution from top percentiles and expectancy after removing top winners.",
    pages: ["quant_lab"],
  },
  {
    id: "top_trade_removal",
    title: "Top-trade removal",
    category: "performance",
    tier: "quant",
    description: "Expectancy and profit factor after removing top N winners.",
    primaryQuestion: "How fragile is performance if best trades are excluded?",
    traderValue: "Stress test for outlier-driven edge.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "table",
    insightEnabled: false,
    methodology: "Counterfactual scenarios removing top 1, 3, and 5 winners from the filtered sample.",
    pages: ["quant_lab"],
  },
  {
    id: "monte_carlo",
    title: "Monte Carlo simulation",
    category: "risk",
    tier: "quant",
    description: "Resampled future return paths and drawdown-at-risk.",
    primaryQuestion: "What drawdowns and ending returns are plausible from this history?",
    traderValue: "Scenario exploration — not a forecast.",
    minimumSampleSize: 5,
    chartType: "line",
    insightEnabled: false,
    methodology: "Resamples historical per-trade returns with replacement across many simulated paths.",
    pages: ["quant_lab"],
  },
  {
    id: "risk_of_ruin",
    title: "Risk of ruin",
    category: "risk",
    tier: "quant",
    description: "Simulated probability of crossing a drawdown ruin threshold.",
    primaryQuestion: "Under fixed % risk, how often might equity cross a ruin threshold?",
    traderValue: "Capital preservation scenario analysis.",
    minimumSampleSize: 5,
    chartType: "metric",
    insightEnabled: false,
    methodology: "Compounding simulation using historical R-multiples and user-defined risk % and ruin threshold.",
    pages: ["quant_lab"],
  },
  {
    id: "drawdown_research",
    title: "Drawdown research",
    category: "risk",
    tier: "quant",
    description: "Maximum drawdown, underwater curve, ulcer index, and recovery factor.",
    primaryQuestion: "How deep and prolonged have drawdowns been?",
    traderValue: "Capital preservation and recovery context.",
    minimumSampleSize: 2,
    chartType: "line",
    insightEnabled: false,
    methodology: "Equity peak-to-trough drawdown series with R-multiple and currency views.",
    pages: ["quant_lab"],
  },
  {
    id: "edge_stability",
    title: "Edge stability",
    category: "edge",
    tier: "quant",
    description: "Recent vs historical expectancy comparison.",
    primaryQuestion: "Is recent performance materially different from my full sample?",
    traderValue: "Early warning for edge decay or improvement.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "metric",
    insightEnabled: false,
    methodology: "Compares rolling recent window metrics against full filtered sample.",
    pages: ["quant_lab"],
  },
  {
    id: "edge_confidence",
    title: "Edge confidence score",
    category: "research",
    tier: "quant",
    description: "Weighted composite of sample, stability, drawdown, and outlier factors.",
    primaryQuestion: "How much statistical confidence does this sample support?",
    traderValue: "Single research summary — not a trading grade.",
    minimumSampleSize: ANALYTICS_MIN_SAMPLE,
    chartType: "bar",
    insightEnabled: false,
    methodology: "Weighted composite score from sample size, edge stability, drawdown, and outlier dependency components.",
    pages: ["quant_lab"],
  },
  {
    id: "walk_forward",
    title: "Walk-forward validation",
    category: "research",
    tier: "quant",
    description: "In-sample vs out-of-sample performance split.",
    primaryQuestion: "Does performance hold on unseen chronological data?",
    traderValue: "Exploratory validation — one split only.",
    minimumSampleSize: 40,
    chartType: "bar",
    insightEnabled: false,
    methodology: "Chronological train/validation split comparing key metrics in-sample vs out-of-sample.",
    pages: ["quant_lab"],
  },
];

export function getAnalyticsDefinition(id: string): AnalyticsDefinition | undefined {
  return ANALYTICS_REGISTRY.find((d) => d.id === id);
}

export function getAnalyticsByPage(page: AnalyticsDefinition["pages"][number]): AnalyticsDefinition[] {
  return ANALYTICS_REGISTRY.filter((d) => d.pages.includes(page));
}

export function getAnalyticsByTier(tier: AnalyticsDefinition["tier"]): AnalyticsDefinition[] {
  return ANALYTICS_REGISTRY.filter((d) => d.tier === tier);
}
